The Equilibrium project is added. An attempt to parse PIK was taken
amtsu/team22 pull request #118
Opened 2023-03-22 09:06 UTC by Andromary

Начала работу над новым проектом. 
В файле is_parsable.ipynb проверяла возможность распарсить застройщиков.
Сначала получалось распарсит ПИК, начала писать соответствующие классы и тесты. НО позже в файле is_parsable.ipynb перестала работать проверка (не распечатывает скачаную страницу).

2023-04-24 15:34 UTC, andreev-alexander commented
```python
# ПИК 
url_check = "https://www.pik.ru/search"
with urllib.request.urlopen(url_check) as page:
    page_text = page.read()
print(page_text)
b_soup = BeautifulSoup(page_text, features="html.parser")
items_list = b_soup.findAll("a", class_ = "styles__FlatCardRow-izq3tk-0 bncElg")
#print(items_list) 
for item in items_list:
    #item_dict = {}
    title_data = item.findAll("div", class_ = "styles__RoomsArea-m4iiyq-1 mKsPL")
    #print(title_data)
    title = title_data[0].text
    #print(title)
```

Если ты про то, что не печатается `print(page_text)`, то он печатается. Это видно, если запустить это в терминале, а не в юпитере.
Не отображается в юпитере, наверное потому что там очень большой ответ и много данных и они не влезают в юпитер. Также судя по всему после `page.read()` в переменной записан ответ в байтах.
Если сделать `print(b_soup)`, то в ответ виден в юпитер.

Ты про это?

2023-04-24 15:39 UTC, andreev-alexander commented
Только написал и [увидел в документации](https://docs.python.org/3/library/urllib.request.html#examples) другое решение - перевести байты в UTF-8 с помощью `.decode('utf-8')`.
После этого в юпитере ответ распечатался

```python
with urllib.request.urlopen(url_check) as page:
    page_text = page.read().decode('utf-8')
print(page_text)
```

2023-08-03 19:39 UTC, isergy requested changes
нужно разрешить конфликты, чтобы принять реквест

2024-01-26 10:06 UTC, isergy approved these changes

2024-01-26 10:07 UTC, merged