Home work 1 samaltsev
amtsu/team22 pull request #119
Opened 2023-03-25 10:10 UTC by SAMalcev

2023-03-30 08:17 UTC, isergy commented
Исходя из того что я видел, когда Серег вы с Артёмом делали коммить последний, нужно ещё раз более внимательно и подробно разобраться с тем, что должно быть в твоей папке.
Ты там какие-то файлы удалил локально, но эти удаления не закоммичены, и если этот пул принять и смержить, удалённые файлы опять восстановятся, но наверное это не нужно.

2023-04-01 01:32 UTC, SAMalcev commented
Наверно я не готов пока понять это, но со временем придёт понимание, спасибо

2023-08-03 19:45 UTC, isergy requested changes
Серж, надо в следующий четверг с этим разобраться и принять )

2023-08-10 18:50 UTC, isergy approved these changes
ок

2023-08-10 18:52 UTC, merged