Home work 1 vstimofeeva
amtsu/team22 pull request #130
Opened 2023-04-07 19:58 UTC by ValliTim

2023-04-08 05:16 UTC, isergy submitted a review, later dismissed
Норм

2023-04-08 05:19 UTC, isergy requested changes
Лишний реквест.

2023-04-09 09:54 UTC, amtsu approved these changes

2023-04-19 14:35 UTC, amtsu approved these changes
OK

2023-04-19 14:36 UTC, amtsu commented
@ValliTim отребейзся

2024-01-26 10:23 UTC, isergy approved these changes

2024-01-26 10:23 UTC, merged