Home work 4 vstimofeeva
amtsu/team22 pull request #132
Opened 2023-04-08 11:00 UTC by ValliTim

2023-04-09 10:03 UTC, amtsu requested changes
Обрати внимание на 7 задание в [users/vstimofeeva/HomeWork_4_function.ipynb]

2023-04-09 10:03 UTC, amtsu commented on users/vstimofeeva/HomeWork_4_function.ipynb
(7) задание - нужно доделать (что если отправлю число 23)  
"Написать функцию is_prime, принимающую 1 аргумент — число, и определяющее, простое оно или составное."

2023-04-19 14:34 UTC, amtsu commented on users/vstimofeeva/HomeWork_4_function.ipynb
@ValliTim  ?

2023-04-22 16:54 UTC, ValliTim commented on users/vstimofeeva/HomeWork_4_function.ipynb
ok. Посмотрю и сделаю до среды 26.04

2024-01-30 13:28 UTC, closed without merging