mvandreeva added hals_parser
amtsu/team22 pull request #154
Opened 2023-05-07 00:45 UTC by Andromary

Пишу парсер для ГАЛС

2023-05-29 15:45 UTC, isergy approved these changes
Круто!!!111111

2023-05-29 15:45 UTC, isergy commented on users/mvandreeva/dags/dag_hals.py
> +    start = BashOperator(task_id="start", bash_command="echo start_load_data_from_hals")
Артём их показывал тогда, но я не вижу смысла в этих операторах, они практически ничего не делают.

2023-05-29 15:45 UTC, isergy commented on users/mvandreeva/dags/dag_hals.py
> +with DAG(dag_id="hals", start_date=datetime(2023, 5, 11), schedule="0 0 * * *") as dag:
а вот тут круто добавлять тэги, например  tags=["sivanov", "parse_22"], так можно свои даги среди всех быстро выделить.

2023-05-29 15:45 UTC, isergy commented on users/mvandreeva/dags/page_parsing.py
> +        b_soup = BeautifulSoup(self.open_page(), features="html.parser")
прочитал вот примерно такое:
The BS module has 2 constructors for this feature, one will accept String and the other will accept the object returned by .urlopen(some-site)

то есть, можно не делать рид, а сохранять то что отдает urlopen. это сократит код open_page(),
но сам я это не пробовал.

2023-05-31 06:38 UTC, Andromary commented on users/mvandreeva/dags/dag_hals.py
> +    start = BashOperator(task_id="start", bash_command="echo start_load_data_from_hals")
> Артём их показывал тогда, но я не вижу смысла в этих операторах, они практически ничего не делают.

Наверно в более сложных дагах будет  больше пользы) а нам , мне казалось, для примера прописывания последовательности операций ввел, ну и начало/конец обозначать, чтоб видно было, на каком этапе что-то ломается...

2023-05-31 06:41 UTC, Andromary commented on users/mvandreeva/dags/dag_hals.py
> +with DAG(dag_id="hals", start_date=datetime(2023, 5, 11), schedule="0 0 * * *") as dag:
О, здорово! Попробую!

2023-05-31 06:42 UTC, Andromary commented on users/mvandreeva/dags/page_parsing.py
> +        b_soup = BeautifulSoup(self.open_page(), features="html.parser")
Может протестирую, сообщу о результатах)

2023-08-03 20:17 UTC, isergy requested changes
после исправления конфликтов срочно в прод!

2023-09-13 12:03 UTC, EANabatov commented
так и должно быть, что много похожих файлов в пуше?

2023-09-16 09:07 UTC, Andromary commented
> так и должно быть, что много похожих файлов в пуше?

Это из-за моего подхода к разработке, сначала в своей папке разрабатываю с проектом, потом копирую файлы в папку с дагами, чтоб данные уже в базу загружались. Возможно, такой подход далёк от идеала...

2023-09-16 09:20 UTC, Andromary commented on users/mvandreeva/dags/page_parsing.py
> +        b_soup = BeautifulSoup(self.open_page(), features="html.parser")
Протестировала, работает, если передавать объект, но Артём мне на это сказал, что по офф.документации нужно передавать текст, поэтому лучше придерживаться документации...

2024-01-26 10:22 UTC, isergy approved these changes

2024-01-26 10:22 UTC, merged