Hw andreev aleksey upd abstract
amtsu/team22 pull request #177
Opened 2023-08-03 04:50 UTC by andreev-aleksey

Чуть поправил класс, чтобы делал что-то осмысленное
- [x] mypy
- [x] pylint

2023-08-03 05:20 UTC, andreev-alexander approved these changes
Вроде норм

2023-08-03 13:58 UTC, Andromary approved these changes
Понравилось, выглядит хорошо

2023-08-03 19:27 UTC, isergy requested changes
Нужно ещё добавить чтение начальных значений из какого-то внешнего источника, и будет топ!

2023-08-03 19:27 UTC, isergy commented on src/simple_model_project/andreev_aleksey_git_module.py
> +        self.__main_number = 13
вот эти параметры бы в какой-то файл с настройками запихнуть и вообще топ будет!

2023-08-04 14:45 UTC, andreev-aleksey commented
@isergy 
Вчера видел твое сообщение в приложении гит, а сейчас не найду по поводу того, что решить конфликты.

Я сделал так:
обновил у себя main 
переключился на эту ветку HW_andreev-aleksey_upd_abstract
сделал merge в main -> HW_andreev-aleksey_upd_abstract
Закоммитил.

Хз почему не дает слить в ветку.
Мб есть варианты?

2023-08-04 15:03 UTC, andreev-aleksey commented
> @isergy Вчера видел твое сообщение в приложении гит, а сейчас не найду по поводу того, что решить конфликты.
> 
> Я сделал так: обновил у себя main переключился на эту ветку HW_andreev-aleksey_upd_abstract сделал merge в main -> HW_andreev-aleksey_upd_abstract Закоммитил.
> 
> Хз почему не дает слить в ветку. Мб есть варианты?

Это я перепутал. 
Видно не у меня был твой комментарий. 
Отбой))

Внес доделку
[добавил чтение параметров из файла](https://github.com/amtsu/team22/pull/177/commits/9cba489dcaff0f6c563531c7b1cd2389c52f046c)

2023-08-05 14:14 UTC, isergy commented on src/simple_model_project/andreev_aleksey_git_module.py
> +ABSOLUTE_PATH = "/home/aleksey/python_projects/team22/src/simple_model_project"
если я попробую запустить этот модуль, то исходные данные прочитать не получится - к этой папке нет доступа. я попробую что-то рассказать про опыт использования полных и относительных путей к файлам внутри программы в следующий раз) сейчас достаточно использовать относительный путь.

2023-09-13 07:59 UTC, EANabatov commented on src/simple_model_project/andreev_aleksey_git_module.py
> +        with open(f"{ABSOLUTE_PATH}/andreev_aleksey_git_module.pickle", "rb") as f:
1. А как ты заносишь данные в пикл?
2. Я правильно понимаю, что в пикле у тебя словарь?

2023-09-13 08:02 UTC, EANabatov commented on src/simple_model_project/andreev_aleksey_git_module.py
> +        if self.__main_number - self.__number_to_check < 0:
МБ стоит тут сделать условие не "<", а "<=" ?

2023-09-13 08:08 UTC, EANabatov commented on src/simple_model_project/andreev_aleksey_git_module.py
> +            raise StopIteration
Возможно я ошибаюсь, но вроде бы эта ошибка работает только с методом `__next__()`. Уверен, что она тут полезна и не путает человека, когда вызывается? Мб стоит написать кастомную ошибку?

2023-09-13 08:09 UTC, EANabatov requested changes
Возможно нужны доработки после обсуждения комментариев

2023-09-16 07:31 UTC, EANabatov approved these changes

2023-09-16 07:31 UTC, isergy approved these changes

2023-09-16 07:31 UTC, merged