Sivanov working with classes
amtsu/team22 pull request #178
Opened 2023-08-03 19:19 UTC by isergy

Ноутбук с занятия про UltraStripper

2023-08-10 18:16 UTC, EANabatov commented
def __repr__(self):
        """
        повторяет __str__, зачем-то был нужен когда отлаживался
        """
        return "repr:" + self.__str__()

Разве у нас self.repr  не должен возвращать строковое представление объекта? 
В данном случае он возвращает строковое представление содержимого данных полученных при инициализации объекта.

2023-08-10 18:24 UTC, EANabatov commented
```
def __do_damage(self, input_data: str) -> str:
        """
        скрытый метод, делающий всю работу по очистке входной строки от нежелательной
        информации, в соответствии с данными, которыми класс был инициализирован
        """
        result = input_data
        for item in **self.__trash_to_remove**:
            result = result.replace(item, "")
        return result.strip()
```
Возможно переменную **self.__trash_to_remove** стоит добавить в вызов метода **def __do_damage**.

2023-08-10 18:41 UTC, EANabatov requested changes
Метод `.repr `требует доработки основываясь на комменте выше.

2023-08-19 23:11 UTC, isergy commented
> Метод `.repr `требует доработки основываясь на комменте выше.
переделал

2023-08-19 23:21 UTC, isergy commented
> ```
> def __do_damage(self, input_data: str) -> str:
>         """
>         скрытый метод, делающий всю работу по очистке входной строки от нежелательной
>         информации, в соответствии с данными, которыми класс был инициализирован
>         """
>         result = input_data
>         for item in self.__trash_to_remove:
>             result = result.replace(item, "")
>         return result.strip()
> ```
> 
> Возможно переменную **self.__trash_to_remove** стоит добавить в вызов метода **def __do_damage**.

нет, не стоит. 
если добавить self.__trash_to_remove в сигнатуру __do_damage, то будет синтаксическая ошибка.
если добавить _trash_to_remove, то потребуется при каждом вызове __do_damage передавать ей как параметры кортеж того, что нужно удалить, а это не то поведение, которое я хотел запрограммировать. если переделать этот класс в функцию, то да, там надо будет.

2023-09-13 07:43 UTC, EANabatov commented
:+1:

2023-09-13 07:44 UTC, EANabatov approved these changes

2023-09-14 18:30 UTC, merged