Agvolodina hw2
amtsu/team22 pull request #359
Opened 2024-02-07 19:32 UTC by Anzhela-Volodina

2024-02-07 21:35 UTC, isergy requested changes
все очень хорошо, но есть лишние файлы, с ними разобраться

2024-02-07 21:35 UTC, isergy commented on library/exercises/theory_console_command.ipynb
изменения в этом файле фиксировать не нужно

2024-02-07 21:35 UTC, isergy commented on users/Untitled1.ipynb
этот файл нужно или перенести в свою папку, или удалить

2024-02-07 21:35 UTC, isergy commented on users/theory_console_command.ipynb
этот файл нужно удалить

2024-02-07 21:35 UTC, isergy commented on users/agvolodina/exercise/hw1/hw_status.txt
врядли этот файл нужен именно тут

2024-02-08 14:28 UTC, Anzhela-Volodina commented
Спасибо за комментарии. Все замечания постаралась исправить. 
Не могу понять почему опять в изменения зафиксированы лишние файлы, фиксировала один файл.

2024-02-08 15:43 UTC, isergy approved these changes

2024-02-08 15:43 UTC, isergy commented on users/agvolodina/exercise/hw3/hw3_part2.ipynb
> [1,2,3,4,5,6,7,8,9,10] [3:7] 
вот это неправильно, остальное прямо норм!

2024-02-08 15:43 UTC, merged