Home work 1 avmorozova
amtsu/team22 pull request #364
Opened 2024-02-07 20:06 UTC by AnnMorozova676

[](url)

2024-02-07 20:47 UTC, VladimirVBykov reviewed
Не хватает файлов result_du result_history
Лишний файл config

2024-02-07 21:28 UTC, isergy requested changes
лишние файлы есть, а так всё ок

2024-02-07 21:28 UTC, isergy commented on README.md
этот файл удалять не нужно.

2024-02-07 21:28 UTC, isergy commented on users/annmorozova676/config
и этот тоже нужно оставить где был

2024-02-07 21:28 UTC, isergy commented on users/avmorozova/config
этот файл не нужен

2024-02-24 08:39 UTC, EANabatov commented
скорректируй ПР и можно принимать

2024-03-25 18:15 UTC, closed without merging