Aavolodin hw5 part3
amtsu/team22 pull request #488
Opened 2024-02-19 19:15 UTC by Andreyvolodinpro

2024-02-19 19:23 UTC, Anzhela-Volodina approved these changes

2024-02-19 19:50 UTC, RomanTarasov91 commented
![image](https://github.com/amtsu/team22/assets/129532014/4d5da972-3c6d-45b5-b2f8-d2eb51c478c1)
ты здесь присваиваешь но вое значение для переменной person. А, как я понял, в задании требуется сравнить значение из предыдущей переменной

2024-02-19 19:54 UTC, RomanTarasov91 commented
![image](https://github.com/amtsu/team22/assets/129532014/abbad94d-6930-4c55-928e-46585bde28cc)
Здесь то же самое

2024-02-19 19:55 UTC, Andromary commented
person = "30"
if person >= "18":
    print("Совершеннолетний")
else:
    print("Несовершеннолетний")
Здесь стоило брать значение возраста из словаря, который определялся ране

for name , price in prices.items():
       if price > '1.5':
            print(f' {name} дорогой товар')
       elif price <= '1.5':
            print(f' {name} приемлемая цена')
О, здорово, питон и строки распознал, отработало правильно)

if 'яйца' in Seven11 and 'батон хлеба' in Seven11 
Тут примечание аналогично тому, что было у Анжелы... Ну и вопрос трактовки задания остается открыт)


students = "Иванов"
if students >= "18":
    print("Совершеннолетний")
else:
    print("Несовершеннолетний")
Мне кажется, здесь каким-то чудом отработало правильно, (надо проверить у себя )а вообще стоило брать ключ-значение из словаря блоком выше и, я бы, дляоднозначности, соавнивала с числом 18, а не строкой.

2024-02-20 09:18 UTC, isergy requested changes
3 задачку надо поправить

2024-02-20 09:18 UTC, isergy commented on users/aavolodin/exercise/hw5/hw5_part3.ipynb
> set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

if set1 > set2:
    print("set1 > set2")
elif set1 < set2:
    print("set2 > set1")
else:
    print("set1 = set2")

неправильно, чтобы убедиться можно попробовать на `set1 = {1, 2, 3, 4, 5, 11,12,13}
set2 = {4, 5, 6, 7, 8}`

>if 'яйца' in Seven11 and 'батон хлеба' in Seven11:
    Seven11['яйца']= Seven11['яйца']-10
    Seven11['батон хлеба']= Seven11['батон хлеба']-1
    print('купил 1 хлеб, осталось', Seven11['батон хлеба'])
    print('купил 10 яиц, осталось', Seven11['яйца'])
else:
    print('хлеба или яиц нет')


здесь стоит проверить, достаточно ли в магазине яиц и хлеба, чтобы их купить

2024-02-25 17:16 UTC, Andreyvolodinpro commented on users/aavolodin/exercise/hw5/hw5_part3.ipynb
3-ю задачку поправил!

2024-02-27 20:22 UTC, isergy approved these changes

2024-02-27 21:03 UTC, Andromary approved these changes

2024-02-27 21:03 UTC, merged