Ismatrosova working time - свой код к себе в папку скопировала, чтоб не потерять
amtsu/team22 pull request #738
Opened 2024-04-10 20:09 UTC by Rikacom

2024-04-10 20:12 UTC, Rikacom commented
Кстати, а я не поняла почему столько изменений....
Буквально два файла добавила 10_04_2024 :(

2024-04-10 20:14 UTC, Rikacom commented
![image](https://github.com/amtsu/team22/assets/94229700/55467d06-b5a7-4c1f-9f34-0469d9a2b629)
в main уже есть предыдущие файлы

2024-04-10 21:50 UTC, isergy reviewed
а так нет проблем

2024-04-10 21:50 UTC, isergy commented on library/working_time/ismatrosova_working_time.py
> +def out_priority_task (list_task):
Этот не нужно коммитить

2024-04-10 21:50 UTC, isergy commented on library/working_time/test_ismatrosova_working_time.py
> +from ismatrosova_working_time import (out_priority_task,)
И этот

2024-04-11 08:30 UTC, Rikacom commented on library/working_time/test_ismatrosova_working_time.py
> +from ismatrosova_working_time import (out_priority_task,)
Это уже в main лежит 😂

2024-04-11 09:37 UTC, isergy commented on library/working_time/test_ismatrosova_working_time.py
> +from ismatrosova_working_time import (out_priority_task,)
тем более

2024-04-12 18:40 UTC, isergy requested changes
файлы из library/working_time/ нужно убрать из этого ПР

2024-04-15 17:06 UTC, isergy commented on users/ismatrosova/exercise/working_time/test_10_04_2024.py
> +    def SumNumberPages(self):
Лучше не испольвать разные стили в названиях методов в одном модуле, а в идеале придерживаться стиля названий, принятого в питоне: https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html

2024-04-15 19:25 UTC, isergy approved these changes

2024-05-02 09:22 UTC, merged