file name fix
amtsu/team22 pull request #912
Opened 2024-09-18 21:46 UTC by find-y

поправил имя файла, чтобы не было конфликта со стандартным модулем питона

2024-09-18 22:14 UTC, AnnaMargolina commented
ok

2024-09-18 22:15 UTC, AnnaMargolina commented
ok

2024-09-18 22:16 UTC, AnnaMargolina approved these changes

2024-10-03 18:59 UTC, EANabatov requested changes
возможны конфликты, наверное проще будет внести эти изменения позже или сделать ветку от обновленного репозитория

2024-10-04 08:50 UTC, closed without merging