Svalekseyeva
amtsu/team22 pull request #99
Opened 2023-02-04 18:59 UTC by SVAlekseyeva

2023-02-05 08:43 UTC, drrryfox approved these changes

2023-08-03 19:30 UTC, isergy requested changes
для этого реквеста нужно разрешить конфликты, тогда его можно будет принять

2023-08-14 11:44 UTC, EANabatov commented
Разрешил конфликт с README.
Можно мержить.

2023-08-14 11:47 UTC, EANabatov approved these changes
OK

2023-08-14 20:30 UTC, isergy approved these changes

2023-08-14 20:30 UTC, merged